# Generated by Django 3.2.6 on 2021-09-07 00:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="get_cat_symbol",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("symbol", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("api_id", models.CharField(blank=True, max_length=100, null=True)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="get_provider_name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oracle.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("market_cap", models.FloatField(blank=True, null=True)),
                (
                    "price_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "market_cap_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="oracle.asset",
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="oracle.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.FloatField(blank=True, null=True)),
                ("max", models.FloatField(blank=True, null=True)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("apy", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ST", "Staking"),
                            ("LP", "Liquidity Providing"),
                            ("INT", "Interest"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oracle.asset"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oracle.service"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="categories",
            field=models.ManyToManyField(to="oracle.Category"),
        ),
    ]
