# Generated by Django 3.2.6 on 2021-11-01 17:38

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="symbol",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("symbol", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("api_id", models.CharField(blank=True, max_length=100, null=True)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Passive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ST", "Staking"),
                            ("LP", "Liquidity Providing"),
                            ("INT", "Interest"),
                        ],
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("min", models.FloatField(blank=True, null=True)),
                ("max", models.FloatField(blank=True, null=True)),
                ("apy_min", models.FloatField()),
                ("apy_max", models.FloatField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oracle.asset"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="get_provider_name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WALT", "Wallet"),
                            ("CHAC", "Checking Account"),
                            ("SAAC", "Savings Account"),
                            ("INAC", "Investment Account"),
                            ("REAC", "Retirement Account"),
                            ("CRAC", "Credit Account"),
                            ("LOAN", "Loan Account"),
                        ],
                        max_length=4,
                    ),
                ),
                ("assets", models.ManyToManyField(blank=True, to="oracle.Asset")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oracle.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassiveChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ADD", "Added"),
                            ("REM", "Removed"),
                            ("CHG", "Changed"),
                        ],
                        max_length=3,
                    ),
                ),
                ("apy_min_change", models.FloatField(blank=True, null=True)),
                ("apy_max_change", models.FloatField(blank=True, null=True)),
                ("min_change", models.FloatField(blank=True, null=True)),
                ("max_change", models.FloatField(blank=True, null=True)),
                (
                    "passive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="oracle.passive",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="passive",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oracle.service"
            ),
        ),
        migrations.CreateModel(
            name="InflationChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change", models.FloatField()),
                ("timestamp", models.DateField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inflation_changes",
                        to="oracle.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("market_cap", models.FloatField(blank=True, null=True)),
                (
                    "price_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "market_cap_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("inflation", models.FloatField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="oracle.asset",
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="oracle.asset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="categories",
            field=models.ManyToManyField(to="oracle.Category"),
        ),
    ]
