# Generated by Django 3.2.6 on 2021-11-01 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("market_cap", models.FloatField(blank=True, null=True)),
                (
                    "price_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "market_cap_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="oracle.asset",
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="oracle.asset",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
