# Generated by Django 3.2.6 on 2021-10-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="inflation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InflationChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change", models.FloatField()),
                ("timestamp", models.DateField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inflation_changes",
                        to="oracle.asset",
                    ),
                ),
            ],
        ),
    ]
