# Generated by Django 3.2.6 on 2021-09-07 08:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from="symbol",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
