# Generated by Django 3.2.6 on 2021-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0002_assetinfo_market_cap_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetinfo",
            name="circulating_supply",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="high_24h",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="low_24h",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="max_supply",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="price_change_percentage_1h",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="price_change_percentage_30d",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="price_change_percentage_7d",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="total_supply",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
