# Generated by Django 3.2.6 on 2021-11-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0002_auto_20211101_0019"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[
                    ("WALT", "Wallet"),
                    ("CHAC", "Checking Account"),
                    ("SAAC", "Savings Account"),
                    ("INAC", "Investment Account"),
                    ("REAC", "Retirement Account"),
                ],
                default="WALT",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
