# Generated by Django 3.2.6 on 2021-09-07 08:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0002_alter_asset_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="asset",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
