# Generated by Django 3.2.6 on 2021-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0002_passive_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="passive",
            name="apy",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
