# Generated by Django 3.2.6 on 2021-09-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0003_passive_apy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passive",
            name="type",
            field=models.CharField(
                choices=[
                    ("ST", "Staking"),
                    ("LP", "Liquidity Providing"),
                    ("INT", "Interest"),
                ],
                max_length=3,
            ),
        ),
    ]
