# Generated by Django 3.2.6 on 2021-09-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0003_alter_asset_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="asset",
            managers=[],
        ),
        migrations.AddField(
            model_name="provider",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
