# Generated by Django 3.2.6 on 2021-11-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0003_auto_20211101_0111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[
                    ("WALT", "Wallet"),
                    ("CHAC", "Checking Account"),
                    ("SAAC", "Savings Account"),
                    ("INAC", "Investment Account"),
                    ("REAC", "Retirement Account"),
                    ("CRAC", "Credit Account"),
                    ("LOAN", "Loan Account"),
                ],
                max_length=4,
            ),
        ),
    ]
