# Generated by Django 3.2.6 on 2021-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0004_auto_20210916_1937"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="assets",
            field=models.ManyToManyField(blank=True, to="oracle.Asset"),
        ),
    ]
