# Generated by Django 3.2.6 on 2021-09-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0004_alter_passive_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="passive",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passive",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
