# Generated by Django 3.2.6 on 2021-09-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0005_auto_20210901_2241"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="api_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
