# Generated by Django 3.2.6 on 2021-09-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0006_auto_20210916_2329"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passive",
            name="apy_max",
        ),
        migrations.RemoveField(
            model_name="passive",
            name="apy_min",
        ),
        migrations.RemoveField(
            model_name="passive",
            name="max",
        ),
        migrations.RemoveField(
            model_name="passive",
            name="min",
        ),
        migrations.RemoveField(
            model_name="passivechange",
            name="apy_max",
        ),
        migrations.RemoveField(
            model_name="passivechange",
            name="apy_min",
        ),
        migrations.RemoveField(
            model_name="passivechange",
            name="max",
        ),
        migrations.RemoveField(
            model_name="passivechange",
            name="min",
        ),
        migrations.CreateModel(
            name="PassiveValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.FloatField(blank=True, null=True)),
                ("max", models.FloatField(blank=True, null=True)),
                ("apy_min", models.FloatField()),
                ("apy_max", models.FloatField(blank=True, null=True)),
                (
                    "passive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oracle.passive"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="passivechange",
            name="value",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.passivevalue",
            ),
            preserve_default=False,
        ),
    ]
