# Generated by Django 3.2.6 on 2021-09-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0006_asset_api_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
