# Generated by Django 3.2.6 on 2021-09-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0007_asset_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="market_cap",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="market_cap_percentage_24h",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="price_change_percentage_24h",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
