# Generated by Django 3.2.6 on 2021-09-16 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0007_auto_20210916_2341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passivevalue",
            name="passive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="oracle.passive",
            ),
        ),
    ]
