# Generated by Django 3.2.6 on 2021-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0008_auto_20210904_0225"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="last_updated",
            field=models.DateField(blank=True, null=True),
        ),
    ]
