# Generated by Django 3.2.6 on 2021-09-20 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0008_alter_passivevalue_passive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passivechange",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change",
                to="oracle.passivevalue",
            ),
        ),
    ]
