# Generated by Django 3.2.6 on 2021-09-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0009_price_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
