# Generated by Django 3.2.6 on 2021-10-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0009_alter_passivechange_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="passive",
            name="apy_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passive",
            name="apy_min",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passive",
            name="max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passive",
            name="min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passivechange",
            name="type",
            field=models.CharField(
                choices=[("ADD", "Added"), ("REM", "Removed"), ("CHG", "Changed")],
                default="ADD",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="passivechange",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="PassiveValue",
        ),
    ]
