# Generated by Django 3.2.6 on 2021-10-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0010_auto_20211003_0523"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passivechange",
            old_name="value",
            new_name="apy_min_change",
        ),
        migrations.AddField(
            model_name="passive",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="passivechange",
            name="apy_max_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passivechange",
            name="max_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passivechange",
            name="min_change",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
