# Generated by Django 3.2.6 on 2021-09-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0010_alter_price_last_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="price",
            old_name="market_cap_percentage_24h",
            new_name="market_cap_change_percentage_24h",
        ),
    ]
