# Generated by Django 3.2.6 on 2021-11-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="smart",
            new_name="dynamic",
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="type",
            field=models.CharField(
                choices=[("AS", "Assets"), ("PL", "Portfolio"), ("DN", "Dynamic")],
                max_length=2,
            ),
        ),
    ]
