# Generated by Django 3.2.6 on 2021-09-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
