# Generated by Django 3.2.6 on 2021-09-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BY", "Buy"),
                    ("SL", "Sell"),
                    ("WD", "Withdraw"),
                    ("DP", "Deposit"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
