# Generated by Django 3.2.6 on 2021-09-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="assets",
            field=models.ManyToManyField(to="oracle.Asset"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="portfolios",
            field=models.ManyToManyField(to="account.Portfolio"),
        ),
    ]
