# Generated by Django 3.2.6 on 2021-11-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0004_alter_service_type"),
        ("account", "0002_auto_20211101_0019"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Wallet",
            new_name="Account",
        ),
        migrations.RenameField(
            model_name="holding",
            old_name="wallet",
            new_name="account",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="wallet",
            new_name="account",
        ),
    ]
