# Generated by Django 3.2.6 on 2021-09-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holding",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="account.wallet",
            ),
        ),
    ]
