# Generated by Django 3.2.6 on 2021-09-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0005_auto_20210901_2241"),
        ("account", "0002_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="fee_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="oracle.asset",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="related",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.transaction",
            ),
        ),
    ]
