# Generated by Django 3.2.6 on 2021-11-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20211101_0139"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="accounts",
            field=models.ManyToManyField(blank=True, to="account.Account"),
        ),
    ]
