# Generated by Django 3.2.6 on 2021-09-06 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "oracle",
            "0011_rename_market_cap_percentage_24h_price_market_cap_change_percentage_24h",
        ),
        ("account", "0003_auto_20210901_2244"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AS", "Assets"),
                            ("PL", "Portfolios"),
                            ("SM", "Smart"),
                        ],
                        max_length=2,
                    ),
                ),
                ("assets", models.ManyToManyField(blank=True, to="oracle.Asset")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.portfolio",
                    ),
                ),
            ],
        ),
    ]
