# Generated by Django 3.2.6 on 2021-09-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="smart",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="type",
            field=models.CharField(
                choices=[("AS", "Assets"), ("PL", "Portfolio"), ("SM", "Smart")],
                max_length=2,
            ),
        ),
    ]
