# Generated by Django 3.2.9 on 2021-11-29 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0005_auto_20211129_2357"),
        ("profile", "0003_watchlist_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="holding",
            name="info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.assetinfo",
            ),
        ),
        migrations.AlterField(
            model_name="holding",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="profile.account",
            ),
        ),
    ]
