# Generated by Django 3.2.9 on 2021-11-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_auto_20211130_0116"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
