# Generated by Django 3.2.9 on 2021-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_portfolioui_watchlistui"),
    ]

    operations = [
        migrations.AddField(
            model_name="holding",
            name="apy_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="holding",
            name="apy_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="holding",
            name="max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="holding",
            name="min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="holding",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="holding",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ST", "Staking"),
                    ("LP", "Liquidity Providing"),
                    ("INT", "Interest"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
