# Generated by Django 3.2.6 on 2021-09-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "oracle",
            "0011_rename_market_cap_percentage_24h_price_market_cap_change_percentage_24h",
        ),
        ("account", "0005_auto_20210906_2303"),
        ("strategy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategytarget",
            name="strategy",
        ),
        migrations.AddField(
            model_name="strategytarget",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="strategytarget",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.asset",
            ),
        ),
        migrations.CreateModel(
            name="StrategyKeyframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.strategy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="strategytarget",
            name="keyframe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="strategy.strategykeyframe",
            ),
            preserve_default=False,
        ),
    ]
