# Generated by Django 3.2.6 on 2021-09-26 02:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("percent", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="strategytarget",
            name="keyframe",
        ),
        migrations.AddField(
            model_name="strategytarget",
            name="strategy",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="strategy.strategy",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="StrategyKeyframe",
        ),
        migrations.AddField(
            model_name="strategyadjustment",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustments",
                to="strategy.strategytarget",
            ),
        ),
    ]
