# Generated by Django 3.2.6 on 2021-10-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0002_auto_20210926_0234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategytarget",
            name="strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="strategy.strategy",
            ),
        ),
    ]
