# Generated by Django 3.2.6 on 2021-10-03 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0003_alter_strategytarget_strategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("change", models.FloatField()),
                ("timestamp", models.DateField()),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="strategy.strategytarget",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StrategyAdjustment",
        ),
    ]
