# Generated by Django 3.2.6 on 2021-10-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0011_auto_20211003_0530"),
        ("strategy", "0004_auto_20211003_0624"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategytarget",
            name="contains",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="_strategy_strategytarget_contains_+",
                to="oracle.Asset",
            ),
        ),
    ]
