# Generated by Django 4.0 on 2021-12-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolioui",
            name="order",
        ),
        migrations.RemoveField(
            model_name="portfolioui",
            name="visibility",
        ),
        migrations.RemoveField(
            model_name="watchlistui",
            name="order",
        ),
        migrations.RemoveField(
            model_name="watchlistui",
            name="visibility",
        ),
        migrations.AddField(
            model_name="portfolioui",
            name="visible_order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="watchlistui",
            name="visible_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
