# Generated by Django 4.0 on 2021-12-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0005_passive_interest_asset_passive_locked_period_and_more"),
        ("user", "0002_remove_portfolioui_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holding",
            name="interest_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="oracle.asset",
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="locked_period",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="holding",
            name="payout_frequency",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
