# Generated by Django 4.1.2 on 2022-12-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_transaction_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="holding",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="user.holding",
            ),
        ),
    ]
