# Generated by Django 4.1.4 on 2022-12-30 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("strategy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="strategy.strategy",
            ),
        ),
        migrations.AddField(
            model_name="strategyui",
            name="strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="strategy.strategy"
            ),
        ),
        migrations.AddField(
            model_name="strategyui",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.portfolio"
            ),
        ),
    ]
