# Generated by Django 4.0 on 2021-12-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("strategy", "0001_initial"),
        ("user", "0001_initial"),
        ("oracle", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyui",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="strategytarget",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.asset",
            ),
        ),
        migrations.AddField(
            model_name="strategytarget",
            name="contains",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="oracle.Asset"
            ),
        ),
        migrations.AddField(
            model_name="strategytarget",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="strategytarget",
            name="strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="strategy.strategy",
            ),
        ),
        migrations.AddField(
            model_name="strategychange",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="strategy.strategytarget",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.portfolio"
            ),
        ),
    ]
