# Generated by Django 4.0 on 2022-01-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0005_passive_interest_asset_passive_locked_period_and_more"),
        ("user", "0004_alter_transaction_account"),
        (
            "strategy",
            "0003_remove_strategyui_order_remove_strategyui_visibility_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StrategyTarget",
            new_name="Target",
        ),
        migrations.RenameModel(
            old_name="StrategyChange",
            new_name="TargetChange",
        ),
    ]
