# Generated by Django 4.0 on 2022-01-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0005_passive_interest_asset_passive_locked_period_and_more"),
        ("strategy", "0004_rename_strategytarget_target_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="targetchange",
            name="target",
        ),
        migrations.AddField(
            model_name="targetchange",
            name="asset",
            field=models.ForeignKey(
                default="02a171fc-8007-11ec-951d-aff958a856a3",
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.asset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="targetchange",
            name="strategy",
            field=models.ForeignKey(
                default="0abbd120-8007-11ec-9096-d7e3fe4c56d4",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="strategy.strategy",
            ),
            preserve_default=False,
        ),
    ]
