# Generated by Django 4.0 on 2022-01-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0005_remove_targetchange_target_targetchange_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetchange",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
