# Generated by Django 4.1.4 on 2023-01-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oracle", "0003_alter_asset_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=5, max_digits=10)),
                ("close", models.DecimalField(decimal_places=5, max_digits=10)),
                ("low", models.DecimalField(decimal_places=5, max_digits=10)),
                ("high", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oracle.asset"
                    ),
                ),
            ],
        ),
    ]
