# Generated by Django 4.1.4 on 2023-01-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_tickdata_history_tic_timesta_581040_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(fields=["asset"], name="history_tic_asset_i_e57a36_idx"),
        ),
    ]
