# Generated by Django 4.1.4 on 2022-12-30 09:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import investigator.oracle.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("value", models.FloatField(blank=True, null=True)),
                ("high_24h", models.FloatField(blank=True, null=True)),
                ("low_24h", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=investigator.oracle.models.get_asset_slug,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("symbol", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("api_id", models.CharField(blank=True, max_length=100, null=True)),
                ("active", models.BooleanField(default=False)),
                ("market_cap_rank", models.IntegerField(blank=True, null=True)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                (
                    "market_cap_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "price_change_percentage_1h",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "price_change_percentage_24h",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "price_change_percentage_7d",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "price_change_percentage_30d",
                    models.FloatField(blank=True, null=True),
                ),
                ("circulating_supply", models.FloatField(blank=True, null=True)),
                ("total_supply", models.FloatField(blank=True, null=True)),
                ("max_supply", models.FloatField(blank=True, null=True)),
                ("inflation", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, populate_from="name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InflationChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change", models.FloatField()),
                ("timestamp", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Passive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.FloatField(blank=True, null=True)),
                ("max", models.FloatField(blank=True, null=True)),
                ("apy_min", models.FloatField(blank=True, null=True)),
                ("apy_max", models.FloatField(blank=True, null=True)),
                ("locked_period", models.DurationField(blank=True, null=True)),
                ("payout_frequency", models.DurationField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ST", "Staking"),
                            ("LP", "Liquidity Providing"),
                            ("INT", "Interest"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PassiveChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ADD", "Added"),
                            ("REM", "Removed"),
                            ("CHG", "Changed"),
                        ],
                        max_length=3,
                    ),
                ),
                ("apy_min_change", models.FloatField(blank=True, null=True)),
                ("apy_max_change", models.FloatField(blank=True, null=True)),
                ("min_change", models.FloatField(blank=True, null=True)),
                ("max_change", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="get_provider_name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WALT", "Wallet"),
                            ("CHAC", "Checking Account"),
                            ("SAAC", "Savings Account"),
                            ("INAC", "Investment Account"),
                            ("REAC", "Retirement Account"),
                            ("CRAC", "Credit Account"),
                            ("LOAN", "Loan Account"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(editable=False, populate_from="name"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oracle.category",
                    ),
                ),
            ],
        ),
    ]
