# Generated by Django 4.1.4 on 2022-12-30 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oracle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="assets",
            field=models.ManyToManyField(blank=True, to="oracle.asset"),
        ),
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oracle.provider"
            ),
        ),
        migrations.AddField(
            model_name="passivechange",
            name="passive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="oracle.passive",
            ),
        ),
        migrations.AddField(
            model_name="passive",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oracle.asset"
            ),
        ),
        migrations.AddField(
            model_name="passive",
            name="interest_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="oracle.asset",
            ),
        ),
        migrations.AddField(
            model_name="passive",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oracle.service"
            ),
        ),
        migrations.AddField(
            model_name="inflationchange",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inflation_changes",
                to="oracle.asset",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.category",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oracle.tag"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="oracle.asset",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="+", to="oracle.tag"),
        ),
    ]
