# Generated by Django 4.0 on 2021-12-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("oracle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="assets",
            field=models.ManyToManyField(blank=True, to="oracle.Asset"),
        ),
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oracle.provider"
            ),
        ),
        migrations.AddField(
            model_name="passivechange",
            name="passive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="oracle.passive",
            ),
        ),
        migrations.AddField(
            model_name="passive",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oracle.asset"
            ),
        ),
        migrations.AddField(
            model_name="passive",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="oracle.service"
            ),
        ),
        migrations.AddField(
            model_name="inflationchange",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inflation_changes",
                to="oracle.asset",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.category",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="oracle.asset",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="tags",
            field=models.ManyToManyField(blank=True, to="oracle.Tag"),
        ),
    ]
