# Generated by Django 4.1.4 on 2023-01-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["active"], name="oracle_asse_active_0d8d49_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["asset_class"], name="oracle_asse_asset_c_bbb15f_idx"
            ),
        ),
    ]
