# Generated by Django 4.0 on 2021-12-24 21:58

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from="symbol",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="+", to="oracle.Tag"),
        ),
    ]
