# Generated by Django 4.0 on 2021-12-24 22:01

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import investigator.oracle.models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0003_alter_asset_id_alter_asset_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_class",
            field=models.ForeignKey(
                default="f803f97a-3785-42b0-815d-8d6945c2e558",
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.tag",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=investigator.oracle.models.get_asset_slug,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
