# Generated by Django 4.1.5 on 2023-03-08 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oracle", "0003_alter_asset_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oracle.asset"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oracle.tag"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                through="oracle.AssetTags",
                to="oracle.tag",
            ),
        ),
    ]
