# Generated by Django 3.2.9 on 2021-11-29 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0004_category_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetinfo",
            name="asset",
        ),
        migrations.AddField(
            model_name="asset",
            name="info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oracle.assetinfo",
            ),
        ),
        migrations.AlterField(
            model_name="assetinfo",
            name="base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="oracle.asset",
            ),
        ),
        migrations.AlterField(
            model_name="assetinfo",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
