# Generated by Django 4.0 on 2021-12-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0004_asset_asset_class_alter_asset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="passive",
            name="interest_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="oracle.asset",
            ),
        ),
        migrations.AddField(
            model_name="passive",
            name="locked_period",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passive",
            name="payout_frequency",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
