# Generated by Django 3.2.9 on 2021-11-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_auto_20211130_0116"),
        ("oracle", "0006_auto_20211130_0116"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssetInfo",
        ),
    ]
