# Generated by Django 3.2.9 on 2021-11-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0007_delete_assetinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="tags",
            field=models.ManyToManyField(blank=True, to="oracle.Tag"),
        ),
    ]
