# Generated by Django 3.2.9 on 2021-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0008_alter_asset_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passive",
            name="apy_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="passive",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ST", "Staking"),
                    ("LP", "Liquidity Providing"),
                    ("INT", "Interest"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
