# Generated by Django 3.2.9 on 2021-12-08 05:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oracle", "0009_auto_20211130_0719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from="api_id",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
